package com.example.handler.command;

public enum BotState {
    // Общие
    IDLE_STOP,
    IDLE_TRACK,

    // Tracks
    TRACKS_ACTION_SELECTION,
    TRACK_SELECT_TYPE,
    TRACK_ENTER_NUMBER,
    TRACK_ENTER_STOP_END,
    TRACK_ENTER_TIME_START,
    TRACK_ENTER_TIME_END,
    TRACK_ENTER_LINK,
    TRACK_ENTER_INTERVAL_WEEKDAYS,
    TRACK_ENTER_INTERVAL_WEEKEND,
    TRACK_UPDATE_SELECT_FIELD,
    TRACK_UPDATE_ENTER_VALUE,
    TRACK_DELETE_SELECT,
    TRACK_UPDATE_ENTER_NEW_VALUE,
    TRACK_ADD_TEXT,
    TRACK_CHANGE_INFO,

    // Stops
    STOPS_ACTION_SELECTION,
    STOP_SELECT_TYPE,
    STOP_SELECT_NUMBER,
    STOP_ENTER_NAME_1,
    STOP_ENTER_NAME_2,
    STOP_UPDATE_SELECT_FIELD,
    STOP_UPDATE_ENTER_VALUE,
    STOP_UPDATE_ENTER_NEW_VALUE,
    STOP_DELETE_NAME
}
